# Generated by Django 6.1.1 on 2026-09-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_page_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Este campo deve ser marcadopara a página ser exibida publicamente'),
        ),
    ]
